#!/usr/bin/env python

import numpy as np
import glob
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Plot particles on axes ax
# p is dictionary of arrays:
#   x,y - position
#   g - circulation
def plot_part(ax, p):
    # plot particles
    n = len(p['x'])
    xy = np.vstack((p['x'], p['y'])).T
    r = 0.005
    pr = np.zeros(n) + r
    coll = matplotlib.collections.EllipseCollection(
        pr, pr, np.zeros(n), offsets=xy, units='x',
        transOffset=ax.transData)
    coll.set_edgecolor('none')

    if 0: # uniform color
        coll.set_facecolor('r')
    else: # color with g
        c = p['g']
        s = np.argsort(c)
        c[s] = np.linspace(-1.,1.,len(s))
        coll.set_array(c)
        coll.set_cmap(plt.cm.bwr)
        coll.set_clim()
    ax.add_collection(coll)
    return

# Plot csv and save to image
# f   - csv path
# fo  - output image path (default: same name with .png)
# Csv should contain columns:
#   x,y - position
#   g - circulation
def plot_csv(f, fo=None):
    if fo is None:
        fo = '.'.join(f.split('.')[:-1]) + ".png"

    # init square figure without axes
    fig = plt.figure(figsize=(5.,5.))
    fig.patch.set_facecolor('k')
    ax = plt.Axes(fig, [0., 0., 1., 1.])
    ax.set_axis_off()
    ax.set_xlim(-1., 1.)
    ax.set_ylim(-1., 1.)
    fig.add_axes(ax)

    # read data
    d = np.genfromtxt(f, delimiter=',', names=True)
    p = {'x':d['x'], 'y':d['y'], 'g':d['g']}

    plot_part(ax, p)

    print(fo)
    fig.savefig(fo, dpi=200, facecolor = fig.get_facecolor())
    plt.close()

def plot_all(p="*.csv"):
    ff = sorted(glob.glob(p))
    for f in ff:
        plot_csv(f)


plot_all()
